### PR TITLE
Make guide overview a `CharField` and the author field uneditable

### PR DESCRIPTION
**Pull request by jchristgit**
This PR makes the `Guide.author` field uneditable - changing it doesn't make any sense, and we don't want users editing it either - and makes the `Guide.overview` field a `CharField`, since it's limited in length to `200` characters.

### CODE REVIEW

**Comment by emmiegit** [comment]
So the author is a special type, reflecting who created the guide?

**Comment by jchristgit** [comment]
What do you mean with `special type`?

**Comment by emmiegit** [comment]
Well I was just wondering how the author is stored. With `CharField` in the title it sort of distracts the mind into thinking "author" is stored as a string, which doesn't seem correct.

**Review by Ma-wa-re — APPROVED** [review]
👍

**Pull request merged**
