### PR TITLE
Use `post` instead of `delete` for delete tests.

### PR DESCRIPTION
**Pull request by jchristgit**
For some reason, two tests used the `DELETE` method instead of `POST` to test the deletion view of guides, this PR fixes that.

### CODE REVIEW

**Comment by emmiegit** [comment]
Why doesn't post deletion use `DELETE`?

**Comment by jchristgit** [comment]
Good question. I actually don't *fully* know myself, but I'm using the generic `DeleteView`, which, and the docs state:

> A view that displays a confirmation page and deletes an existing object. The given object will only be deleted if the request method is POST. If this view is fetched via GET, it will display a confirmation page that should contain a form that POSTs to the same URL.

So yeah. I don't fully know either.

**Comment by emmiegit** [comment]
lol

**Review by emmiegit — APPROVED** [review]

**Comment by jchristgit** [comment]
Turns out I was wrong. Judging from the `DeletionMixin`s source code (used in `DeleteView`), the desired behaviour seems to be the `delete` action, and `post` seems to be recommended for compatibility reasons:
```py
class DeletionMixin:
    """Provide the ability to delete objects."""
    success_url = None

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

    # Add support for browsers which only accept GET and POST for now.
    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        if self.success_url:
            return self.success_url.format(**self.object.__dict__)
        else:
            raise ImproperlyConfigured(
                "No URL to redirect to. Provide a success_url.")
```

If wanted, I can change that. I highly doubt any modern browser does not support `DELETE`...

**Comment by emmiegit** [comment]
I would add both in that case.

**Comment by jchristgit** [comment]
good idea. will do that

**Pull request merged**
